import { forwardRef, Fragment, type ReactNode, useEffect, useState } from "react";
import { format } from "date-fns";
import { ptBR } from "date-fns/locale";
import { MapPin, Link as LinkIcon } from "lucide-react";

const renderRich = (text: string, boldClass = "font-semibold text-vink"): ReactNode => text.split(/(\*\*[^*]+\*\*|❤️)/g).map((part, i) => part === "❤️" ? <span key={i} aria-label="coração" className="ml-1 inline-block font-serif text-[0.9em] not-italic leading-none text-[#b91c1c] [-webkit-text-stroke:0.55px_#111827]">♥</span> : part.startsWith("**") && part.endsWith("**") && part.length > 4 ? <strong key={i} className={boldClass}>{part.slice(2, -2)}</strong> : <Fragment key={i}>{part}</Fragment>);
const Lotus = ({ className }: { className?: string }) => <svg viewBox="0 0 24 24" className={className} fill="currentColor" aria-hidden="true"><path d="M12 3.2c1.5 1.7 2.3 3.5 2.3 5.4 0 1.4-.4 2.7-1.2 4 .1-2.4-.3-4.5-1.1-6.2-.8 1.7-1.2 3.8-1.1 6.2-.8-1.3-1.2-2.6-1.2-4 0-1.9.8-3.7 2.3-5.4Zm-6.8 4c1.9.4 3.4 1.3 4.5 2.6 1.1 1.3 1.5 2.4 1.5 3.4-1.4-1.5-3-2.5-4.7-3 .9 1.4 2 2.6 3.3 3.5-1.4.1-2.7-.2-3.9-.9C4.6 12 3.8 10.2 3.4 8c.6-.4 1.2-.6 1.8-.8Zm13.6 0c.6.2 1.2.4 1.8.8-.4 2.2-1.2 4-2.5 4.8-1.2.7-2.5 1-3.9.9 1.3-.9 2.4-2.1 3.3-3.5-1.7.5-3.3 1.5-4.7 3 .2-1.3.7-2.4 1.5-3.4ZM12 14.6c2.4 0 4.6.8 6.4 2.2-1.8 2.1-4 3.2-6.4 3.2s-4.6-1.1-6.4-3.2c1.8-1.4 4-2.2 6.4-2.2Z" /></svg>;
interface VoucherCardProps { clientName: string; code: string; expiresAt: string; serviceName?: string; voucherType?: string; discountAmount?: number | null; title?: string | null; message?: string | null; highlightMessage?: string | null; serviceDescription?: string | null; }
const VoucherCard = forwardRef<HTMLDivElement, VoucherCardProps>((props, ref) => {
 const { clientName, code, expiresAt, serviceName="Experiência Completa em Limpeza de Pele", voucherType="presente", discountAmount, title, message, highlightMessage, serviceDescription }=props;
 const isDiscount=voucherType==="desconto"; const whatsappText=isDiscount?`Oi! Eu recebi um voucher de desconto de R$${discountAmount??30},00 e gostaria de agendar. O código do voucher é ${code}`:`Oi! Eu recebi um voucher para realizar ${serviceName} e gostaria de agendar. O código do voucher é ${code}`;
 const defaultMessage=isDiscount?"Este é um pequeno gesto para você.":"Filha, esse é um pequeno gesto para lembrar o quanto você é especial para mim."; const typedMessage=message?.trim()||defaultMessage; const typedHighlight=highlightMessage?.trim()||"Aproveite esse momento, você merece! ❤️"; const serviceText=serviceDescription?.trim()||(isDiscount?`Esse voucher dá direito a **R$ ${discountAmount??30},00** de desconto no seu próximo procedimento.`:`Esse voucher dá direito a **1 sessão** de uma **${serviceName}**, com duração de 1h30 a 2h.`);
 const [typedText,setTypedText]=useState(""); const [showHighlight,setShowHighlight]=useState(false); const [showRest,setShowRest]=useState(false);
 useEffect(()=>{let cancelled=false; setTypedText("");setShowHighlight(false);setShowRest(false);let index=0;let timer:number;const typeNext=()=>{if(cancelled)return;if(index<typedMessage.length){index++;setTypedText(typedMessage.slice(0,index));const previous=typedMessage[index-1];const delay=previous===","?850:previous==="."?600:72;timer=window.setTimeout(typeNext,delay);}else{timer=window.setTimeout(()=>{if(!cancelled)setShowHighlight(true);},700);window.setTimeout(()=>{if(!cancelled)setShowRest(true);},2100);}};timer=window.setTimeout(typeNext,900);return()=>{cancelled=true;window.clearTimeout(timer);};},[typedMessage]);
 return <div ref={ref} className="relative mx-auto flex w-full max-w-[360px] flex-col items-center bg-white px-7 py-6" style={{aspectRatio:"9/16"}}>
  <div className="pointer-events-none absolute inset-[10px] rounded-[14px] border border-vink/45"/><div className="pointer-events-none absolute inset-[15px] rounded-[11px] border border-vink/25"/>
  <div className={`w-full transition-opacity duration-[1800ms] ${showRest?"opacity-100":"opacity-0"}`}><img src="/logo-grazielle.jpg" alt="Grazielle Diniz - Estética Avançada & Laser" className="mx-auto mt-1 h-[92px] w-[92px] rounded-full object-cover"/>{title?.trim()&&<h1 className="mt-3 text-center font-allura text-[30px] leading-tight text-vink">{renderRich(title!)}</h1>}</div>
  <p className="mt-5 min-h-[54px] w-full whitespace-pre-line text-center font-sans text-[22px] font-normal leading-[1.22] tracking-[0.005em] text-vink">{renderRich(typedText)}</p>
  <p className={`mt-3 min-h-[31px] w-full whitespace-pre-line text-center font-cursive text-[27px] font-medium leading-[1.15] text-vink transition-all duration-[1800ms] ease-out ${showHighlight?"translate-y-0 opacity-100":"translate-y-2 opacity-0"}`}>{showHighlight?renderRich(typedHighlight,"text-vink"):"\u00a0"}</p>
  <div className={`w-full transition-all duration-[2200ms] ease-out ${showRest?"translate-y-0 opacity-100":"translate-y-3 opacity-0"}`}>
   <div className="my-4 flex items-center justify-center gap-2.5"><div className="h-px w-14 bg-vink/50"/><div className="h-[5px] w-[5px] rounded-full bg-vink/70"/><div className="h-px w-14 bg-vink/50"/></div>
   <p className="whitespace-pre-line text-center font-body text-[12.5px] font-normal leading-[1.5] text-vbody">{renderRich(serviceText)}</p>
   <p className="mt-4 text-center font-body text-[10px] font-medium uppercase tracking-[0.22em] text-vsoft">Código do voucher</p><div className="mt-1.5 flex justify-center"><div className="rounded-lg border border-dotted border-vink/60 px-8 py-1"><span className="font-serif text-[22px] font-bold tracking-[0.14em] text-vink">{code}</span></div></div>
   <p className="mt-3 text-center font-body text-[10px] font-medium uppercase tracking-[0.22em] text-vsoft">Para</p><p className="mt-0.5 text-center font-serif text-[27px] font-bold leading-tight text-vink">{clientName}</p>
   <p className="mt-2 text-center font-serif text-[12.5px] italic text-vbody">{isDiscount?"\u201cCuide-se, você merece.\u201d":"\u201cUm momento de renovação, cuidado e autoestima.\u201d"}</p>
   <div className="mt-3 flex w-full items-center justify-center gap-3"><div className="h-px w-16 bg-vink/40"/><Lotus className="h-4 w-4 text-vink"/><div className="h-px w-16 bg-vink/40"/></div><p className="mt-2 text-center font-body text-[11px] text-vbody">Esse voucher é pessoal e intransferível.</p><div className="min-h-2 flex-1"/>
   <div className="flex justify-center"><a href={`https://wa.me/5513991630136?text=${encodeURIComponent(whatsappText)}`} target="_blank" rel="noopener noreferrer" className="group relative inline-flex items-center justify-center overflow-hidden rounded-md bg-vink px-8 py-2 font-body text-[13px] font-semibold text-background shadow-sm transition-opacity hover:opacity-90"><span className="absolute inset-0 -translate-x-full animate-[shine_3s_ease-in-out_infinite] bg-gradient-to-r from-transparent via-white/25 to-transparent"/>Agendar</a></div>
   <p className="mt-3 text-center font-body text-[9px] font-medium uppercase tracking-[0.2em] text-vsoft">Conhecer Grazielle Diniz</p><div className="flex justify-center"><a href="https://esteticagraziellediniz.com/bio/" target="_blank" rel="noopener noreferrer" className="mt-1 inline-flex items-center gap-1.5 rounded-md border border-vink/40 px-4 py-1 font-body text-[10.5px] font-medium text-vink transition-colors hover:bg-vline/60"><LinkIcon className="h-3 w-3"/>esteticagraziellediniz.com/bio</a></div>
   <div className="mt-3 w-full space-y-1 text-center font-body text-[10px] text-vbody"><p>Válido até: <span className="font-semibold text-vink">{format(new Date(expiresAt),"dd/MM/yyyy",{locale:ptBR})}</span></p><div className="flex items-center justify-center gap-1"><MapPin className="h-3 w-3 shrink-0 text-vsoft"/><span>Av. Dom Pedro I, 1785 - Sl 406 - Enseada, Guarujá - SP</span></div></div>
  </div>
 </div>;
});
VoucherCard.displayName="VoucherCard"; export default VoucherCard;
